name: Continuous Integration and Delivery

on: [push]

jobs:
  run_example_site_tests:
    if: github.ref == 'refs/heads/develop'
    name: Run Django-Address Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: 'refs/heads/develop'
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run tests
        run: python example_site/manage.py test example_site/
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
